package generatededitguard

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/HappyOnigiri/hhx/internal/hooktest"
	"github.com/HappyOnigiri/hhx/internal/i18n"
)

func TestMain(m *testing.M) {
	os.Exit(hooktest.Main(m))
}

// l10nConfig は独自のマーカー（make l10n の生成物）を足す設定である。
const l10nConfig = "hooks:\n  generated-edit-guard:\n    markers:\n      - \"^// auto generate by 'make l10n'\"\n"

const (
	standardHeader = "// Code generated by acme-gen. DO NOT EDIT.\n\npackage acme\n"
	mockHeader     = "// Code generated by MockGen. DO NOT EDIT.\n// Source: acme.go\n//\n// Generated by this command:\n//\n" +
		"//\tmockgen -source=acme.go -destination=x_mock.go\n//\n\npackage acme\n"
	l10nHeader = "// auto generate by 'make l10n' on repository root directory.\npackage l10n\n"
)

// fixture は生成ファイルとそうでないファイルを置いた作業ディレクトリと、宣言の置き場である。
type fixture struct {
	dir string
}

func newFixture(t *testing.T) *fixture {
	t.Helper()
	tmp := hooktest.TempDir(t)
	t.Setenv("XDG_CACHE_HOME", filepath.Join(tmp, "cache"))
	f := &fixture{dir: filepath.Join(tmp, "work")}
	files := map[string]string{
		"gen.go":                             standardHeader,
		"x_mock.go":                          mockHeader,
		"infrastructure/l10n/resource_ja.go": l10nHeader,
		"infrastructure/l10n/translation.go": l10nHeader,
		"sub/gen.go":                         standardHeader,
		"plain.go":                           "package acme\n",
		"tmp.go":                             "package acme\n",
		"scripts/gen.py":                     "print('generate')\n",
	}
	for name, content := range files {
		hooktest.WriteFile(t, filepath.Join(f.dir, name), content)
	}
	return f
}

func (f *fixture) path(name string) string {
	return filepath.Join(f.dir, name)
}

// payload は session の PreToolUse の payload を作る。
func (f *fixture) payload(session, toolName string, toolInput any) string {
	data, err := json.Marshal(map[string]any{
		"session_id":      session,
		"transcript_path": "/dev/null",
		"hook_event_name": "PreToolUse",
		"tool_name":       toolName,
		"tool_input":      toolInput,
		"cwd":             f.dir,
	})
	if err != nil {
		panic(err)
	}
	return string(data)
}

func (f *fixture) bash(session, command string) string {
	return f.payload(session, "Bash", map[string]any{"command": command})
}

// invoke は payload で起動し、判定を返す。出力が注入なら、判断のフィールドが無いことを確かめて Injection も返す。
func invoke(t *testing.T, raw string, options hooktest.Options) (hooktest.Result, hooktest.Injection) {
	t.Helper()
	output := hooktest.Output(t, Definition(), raw, options)
	if strings.Contains(output, "permissionDecision") {
		return hooktest.Run(t, Definition(), raw, options), hooktest.Injection{}
	}
	return hooktest.Result{}, hooktest.ParseInjection(t, output)
}

func expectDeny(t *testing.T, raw string, options hooktest.Options, contains ...string) string {
	t.Helper()
	result, injection := invoke(t, raw, options)
	if result.Decision != hooktest.Deny {
		t.Fatalf("decision=%q, want deny (context %q) for %s", result.Decision, injection.Context, raw)
	}
	for _, text := range contains {
		if !strings.Contains(result.Reason, text) {
			t.Errorf("reason %q does not contain %q", result.Reason, text)
		}
	}
	return result.Reason
}

func expectSilent(t *testing.T, raw string, options hooktest.Options) {
	t.Helper()
	if output := hooktest.Output(t, Definition(), raw, options); output != "" {
		t.Errorf("want no output for %s, got %q", raw, output)
	}
}

func expectInjection(t *testing.T, raw string, options hooktest.Options) string {
	t.Helper()
	result, injection := invoke(t, raw, options)
	if result.Decision != "" || injection.Event != "PreToolUse" || injection.Context == "" {
		t.Fatalf("want an injection without a decision, got decision=%q injection=%+v (reason %q)",
			result.Decision, injection, result.Reason)
	}
	return injection.Context
}

func withL10n() hooktest.Options {
	return hooktest.Options{Config: l10nConfig}
}

// --- 編集ツール -----------------------------------------------------------------

func TestEditToolsDenyGeneratedFiles(t *testing.T) {
	f := newFixture(t)
	for _, toolName := range []string{"Edit", "Write", "MultiEdit"} {
		raw := f.payload("s", toolName, map[string]any{"file_path": f.path("gen.go"), "content": "x"})
		expectDeny(t, raw, hooktest.Options{}, "gen.go", `"// Code generated by acme-gen. DO NOT EDIT."`)
	}
	notebook := f.payload("s", "NotebookEdit", map[string]any{"notebook_path": f.path("gen.go"), "new_source": "x"})
	expectDeny(t, notebook, hooktest.Options{}, "gen.go")
	// 相対パスは payload の cwd から解決する。
	expectDeny(t, f.payload("s", "Edit", map[string]any{"file_path": "sub/gen.go"}), hooktest.Options{}, "sub/gen.go")
}

func TestEditToolConfigMarker(t *testing.T) {
	f := newFixture(t)
	raw := f.payload("s", "Edit", map[string]any{"file_path": f.path("infrastructure/l10n/translation.go")})
	expectDeny(t, raw, withL10n(), "infrastructure/l10n/translation.go", "`make l10n`")
	// 設定のマーカーが無ければ、独自のマーカーは生成ファイルとみなさない。
	expectSilent(t, raw, hooktest.Options{})
}

func TestEditToolsPassOtherFiles(t *testing.T) {
	f := newFixture(t)
	for _, raw := range []string{
		f.payload("s", "Edit", map[string]any{"file_path": f.path("plain.go")}),
		f.payload("s", "Write", map[string]any{"file_path": f.path("new.go"), "content": standardHeader}),
		f.payload("s", "Write", map[string]any{"file_path": f.path("sub"), "content": "x"}),
		f.payload("s", "Edit", map[string]any{"file_path": ""}),
		f.payload("s", "Edit", map[string]any{"file_path": 3}),
		f.payload("s", "Edit", "not an object"),
	} {
		expectSilent(t, raw, hooktest.Options{})
	}
}

func TestApplyPatch(t *testing.T) {
	f := newFixture(t)
	patch := func(header string) string {
		return f.payload("s", "apply_patch", map[string]any{"command": "*** Begin Patch\n" + header + "\n@@\n-a\n+b\n*** End Patch\n"})
	}
	expectDeny(t, patch("*** Update File: gen.go"), hooktest.Options{}, "gen.go")
	expectDeny(t, patch("*** Delete File: "+f.path("x_mock.go")), hooktest.Options{}, "x_mock.go",
		"`mockgen -source=acme.go -destination=x_mock.go`")
	expectDeny(t, patch("*** Update File: infrastructure/l10n/resource_ja.go"), withL10n(), "`make l10n`")
	expectSilent(t, patch("*** Add File: brand-new.go"), hooktest.Options{})
	expectSilent(t, patch("*** Update File: plain.go"), hooktest.Options{})
	// tool_input が文字列でも、中の見出しを読む。
	expectDeny(t, f.payload("s", "apply_patch", "*** Begin Patch\n*** Update File: gen.go\n*** End Patch"),
		hooktest.Options{}, "gen.go")
}

// --- Bash ---------------------------------------------------------------------

// opus1Command は、生成ファイルをその場のコードで書き換えた実例と同じ形である。
func opus1Command(dir string) string {
	return "cd " + dir + "; python3 - <<'EOF'\n" +
		"p='infrastructure/l10n/resource_ja.go'\n" +
		"s=open(p,encoding='utf-8').read()\n" +
		"s=s.replace('\"a\"','\"b\"')\n" +
		"open(p,'w',encoding='utf-8').write(s)\n" +
		"EOF"
}

func TestOpus1Heredoc(t *testing.T) {
	f := newFixture(t)
	// Codex と同じく、payload の cwd はセッション開始時の別のディレクトリのままで、cd で移る。
	raw, err := json.Marshal(map[string]any{
		"session_id": "s", "tool_name": "Bash", "cwd": hooktest.TempDir(t),
		"tool_input": map[string]any{"command": opus1Command(f.dir)},
	})
	if err != nil {
		t.Fatal(err)
	}
	expectDeny(t, string(raw), withL10n(), "infrastructure/l10n/resource_ja.go", "`make l10n`")
}

func TestBashWritesAreDenied(t *testing.T) {
	f := newFixture(t)
	other := hooktest.TempDir(t)
	cases := []hooktest.Case{
		{Command: "sed -i 's/a/b/' x_mock.go", Label: "x_mock.go"},
		{Command: "echo x >> gen.go", Label: "gen.go"},
		{Command: "cat a | tee gen.go", Label: "gen.go"},
		{Command: "cp tmp.go gen.go", Label: "gen.go"},
		{Command: "echo x > gen.go"},
		{Command: "echo x >gen.go"},
		{Command: "printf x >| gen.go"},
		{Command: "echo x &> gen.go"},
		{Command: "echo x &>> gen.go"},
		{Command: "cat missing 2> gen.go"},
		{Command: "echo x >& gen.go"},
		{Command: "echo x > " + f.path("gen.go")},
		{Command: "echo x > './gen.go'"},
		{Command: "echo x > \"sub/\"gen.go"},
		{Command: "cat > gen.go <<'EOF'\npackage acme\nEOF"},
		{Command: "sed -i '' 's/a/b/' gen.go"},
		{Command: "sed -i.bak -e 's/a/b/' gen.go"},
		{Command: "sed -Ei 's/a/b/' gen.go"},
		{Command: "sed --in-place 's/a/b/' gen.go"},
		{Command: "gsed -i 's/a/b/' plain.go gen.go"},
		{Command: "sed -i 's/a/b/' *.go"},
		{Command: "FOO=1 sed -i 's/a/b/' gen.go"},
		{Command: "sudo -u root sed -i 's/a/b/' gen.go"},
		{Command: "env LC_ALL=C sed -i 's/a/b/' gen.go"},
		{Command: "timeout 10 sed -i 's/a/b/' gen.go"},
		{Command: "perl -pi -e 's/a/b/' gen.go"},
		{Command: "perl -i.bak -pe 's/a/b/' gen.go"},
		{Command: "tee -a gen.go < /dev/null"},
		{Command: "mv tmp.go gen.go"},
		{Command: "cp -f tmp.go gen.go"},
		{Command: "cp gen.go sub/"},
		{Command: "cp -t sub gen.go"},
		{Command: "install -m 644 tmp.go gen.go"},
		{Command: "truncate -s 0 gen.go"},
		{Command: "dd if=/dev/zero of=gen.go bs=1 count=1"},
		{Command: "python3 -c \"open('gen.go','w').write('x')\""},
		{Command: "python3 -c \"import pathlib; pathlib.Path('gen.go').write_text('x')\""},
		{Command: "python -c \"import shutil; shutil.copy('tmp.go', 'gen.go')\""},
		{Command: "node -e \"require('fs').writeFileSync('gen.go', 'x')\""},
		{Command: "node --eval=\"require('fs').appendFileSync('gen.go', 'x')\""},
		{Command: "ruby -e \"File.write('gen.go', 'x')\""},
		{Command: "perl -e 'open(my $f, \">\", \"gen.go\"); print $f \"x\"'"},
		{Command: "python3 <<'EOF'\nopen('gen.go', 'w').write('x')\nEOF"},
		{Command: "cat <<'EOF' | python3 -\nwith open('gen.go', 'a') as f:\n    f.write('x')\nEOF"},
		{Command: "python3 - <<< \"open('gen.go','w').write('x')\""},
		{Command: "echo \"open('gen.go','w').write('x')\" | python3"},
		{Command: "cd sub && echo x > gen.go"},
		{Command: "cd " + other + " && cd " + f.dir + "/sub && echo x > gen.go"},
		{Command: "(cd sub; echo x > gen.go)"},
		{Command: "pushd sub && echo x > gen.go"},
		{Command: "bash -c 'echo x > gen.go'"},
		{Command: "sh -lc \"sed -i 's/a/b/' gen.go\""},
		{Command: "eval 'echo x > gen.go'"},
		{Command: "echo $(echo x > gen.go)"},
		{Command: "if true; then echo x > gen.go; fi"},
		{Command: "git apply <<'EOF'\n--- a/gen.go\n+++ b/gen.go\n@@ -1 +1 @@\n-a\n+b\nEOF"},
		{Command: "git -C sub apply <<'EOF'\ndiff --git a/gen.go b/gen.go\n--- a/gen.go\n+++ b/gen.go\nEOF"},
		{Command: "cat <<'EOF' | patch -p1\n--- a/gen.go\n+++ b/gen.go\t2026-10-03\nEOF"},
		{Command: "patch gen.go fix.diff"},
		{Command: "patch -p0 <<'EOF'\n--- gen.go\n+++ gen.go\nEOF"},
		{Command: "apply_patch <<'EOF'\n*** Begin Patch\n*** Update File: gen.go\n*** End Patch\nEOF"},
		{Command: "ls\necho x > gen.go"},
		{Command: "echo x > gen.go\n"},
		{Command: "> gen.go"},
		{Command: "FOO=1 > gen.go"},
		{Command: "(echo x) > gen.go"},
		{Command: "{ echo x; } > gen.go"},
		{Command: "for f in a; do echo $f; done > gen.go"},
		{Command: "awk '{print}' tmp.go > gen.go"},
		{Command: "sed 's/a/b/' gen.go > gen.go"},
		{Command: "python3 -c 'print(1)' > gen.go"},
		{Command: "node -e 'console.log(1)' >> gen.go"},
		{Command: "sed 's/a/b/' gen.go | sponge gen.go"},
	}
	hooktest.CheckTable(t, Definition(), hooktest.Deny, f.dir, cases)
}

func TestBashPatchFiles(t *testing.T) {
	f := newFixture(t)
	diff := "--- a/gen.go\n+++ b/gen.go\n@@ -1 +1 @@\n-a\n+b\n"
	hooktest.WriteFile(t, f.path("fix.diff"), diff)
	hooktest.CheckTable(t, Definition(), hooktest.Deny, f.dir, hooktest.Commands(
		"git apply fix.diff",
		"git apply --index fix.diff",
		"patch -p1 -i fix.diff",
		"patch -p1 < fix.diff",
		"cat fix.diff | git apply",
	))
	hooktest.CheckTable(t, Definition(), "", f.dir, hooktest.Commands(
		"git apply --check fix.diff",
		"git apply --stat fix.diff",
		"git apply --cached fix.diff",
		"patch -p1 -o out.go -i fix.diff",
	))
}

func TestBashReadsAndRegenerationPass(t *testing.T) {
	f := newFixture(t)
	other := hooktest.TempDir(t)
	hooktest.CheckTable(t, Definition(), "", f.dir, hooktest.Commands(
		"grep -n foo gen.go",
		"sed -n 1,20p gen.go",
		"sed 's/a/b/' gen.go",
		"sed 's/a/b/' gen.go > out.go",
		"git diff gen.go",
		"cat gen.go",
		"cat gen.go 2>/dev/null",
		"make l10n",
		"make autogen",
		"go generate ./...",
		"python3 scripts/gen.py",
		"python3 scripts/gen.py > out.txt",
		"python3 scripts/gen.py > gen.go",
		"python3 -m acme.gen > gen.go",
		"mockgen -source=acme.go > x_mock.go",
		"go run ./cmd/gen > gen.go",
		"./gen.sh > gen.go",
		"git show HEAD:gen.go > gen.go",
		"make build &> gen.go",
		"python3 -m acme.gen",
		"python3 -c \"print(open('gen.go').read())\"",
		"python3 -c \"s=open('gen.go').read(); print(s)\"",
		"echo x > plain.go",
		"echo x > new.go",
		"echo x >&2",
		"echo x 2>&1",
		"echo x > /dev/null",
		"cp gen.go copy.go",
		"cp gen.go "+other,
		"mv tmp.go other.go",
		"install -d sub",
		"tee out.log",
		"cd "+other+" && echo x > gen.go",
		"cd sub && cat gen.go",
		"(cd "+other+"); echo x > plain.go",
		"echo 'x > gen.go'",
		"echo x > $FILE",
		"echo x > \"$(pwd)\"/gen.go",
		"# echo x > gen.go",
		"perl -ne 'print' gen.go",
		"ruby -e 'puts File.read(\"gen.go\")'",
		"node -e \"console.log(require('fs').readFileSync('gen.go', 'utf8'))\"",
	))
}

// TestCdKeepsDirectoryWhenUnresolved は、行き先の決まらない cd では作業ディレクトリを変えないことを固定する。
func TestCdKeepsDirectoryWhenUnresolved(t *testing.T) {
	f := newFixture(t)
	hooktest.CheckTable(t, Definition(), hooktest.Deny, f.dir, hooktest.Commands(
		"cd $DIR && echo x > gen.go",
		"cd no-such-dir; echo x > gen.go",
		"cd - && echo x > gen.go",
	))
	hooktest.CheckTable(t, Definition(), hooktest.Deny, hooktest.TempDir(t), hooktest.Commands(
		"cd "+f.dir+" && cd sub && cd .. && echo x > gen.go",
	))
}

// --- 宣言によるスキップ ----------------------------------------------------------------

func declare(paths string) string {
	return "hhx " + DeclareCommand + " --reason 'the user asked to patch the generated file' " + paths
}

func TestDeclarationAllowsEditsInTheSameSession(t *testing.T) {
	f := newFixture(t)
	language := hooktest.Language
	declared := expectInjection(t, f.bash("session-a", declare("gen.go")), hooktest.Options{})
	if want := messages.T(language, idContextDeclared); !strings.Contains(declared, want) {
		t.Errorf("context %q does not contain %q", declared, want)
	}
	for _, want := range []string{"gen.go", "the user asked to patch the generated file", messages.T(language, idUnknownCommand)} {
		if !strings.Contains(declared, want) {
			t.Errorf("context %q does not contain %q", declared, want)
		}
	}

	for _, raw := range []string{
		f.payload("session-a", "Edit", map[string]any{"file_path": f.path("gen.go")}),
		f.bash("session-a", "echo x >> gen.go"),
		f.bash("session-a", "cd sub && echo x >> ../gen.go"),
	} {
		allowed := expectInjection(t, raw, hooktest.Options{})
		if want := messages.T(language, idContextAllowed); !strings.Contains(allowed, want) {
			t.Errorf("context %q does not contain %q", allowed, want)
		}
		if !strings.Contains(allowed, "the user asked to patch the generated file") {
			t.Errorf("context %q does not carry the declared reason", allowed)
		}
	}

	// 別のセッションと、宣言していないパスは止める。宣言したパスと一緒に書いても止める。
	expectDeny(t, f.payload("session-b", "Edit", map[string]any{"file_path": f.path("gen.go")}), hooktest.Options{})
	expectDeny(t, f.payload("session-a", "Edit", map[string]any{"file_path": f.path("sub/gen.go")}), hooktest.Options{})
	reason := expectDeny(t, f.bash("session-a", "echo x | tee gen.go x_mock.go"), hooktest.Options{}, "x_mock.go")
	if strings.Contains(reason, "Blocked: "+messages.Text(language, idTarget, map[string]any{"Files": "gen.go"})) {
		t.Errorf("the declared path must not be listed as blocked: %q", reason)
	}
}

func TestDeclarationReportMentionsGeneratorCommand(t *testing.T) {
	f := newFixture(t)
	declared := expectInjection(t, f.bash("s", declare("infrastructure/l10n/resource_ja.go")), withL10n())
	if !strings.Contains(declared, "`make l10n`") {
		t.Errorf("context %q does not name the generator command", declared)
	}
	allowed := expectInjection(t, f.bash("s", opus1Command(f.dir)), withL10n())
	if !strings.Contains(allowed, "`make l10n`") || !strings.Contains(allowed, "infrastructure/l10n/resource_ja.go") {
		t.Errorf("context %q does not describe the allowed edit", allowed)
	}
}

func TestDeclarationAndWriteInOneCommand(t *testing.T) {
	f := newFixture(t)
	context := expectInjection(t, f.bash("s", declare(f.path("gen.go"))+" && echo x >> gen.go"), hooktest.Options{})
	language := hooktest.Language
	for _, id := range []string{idContextDeclared, idContextAllowed} {
		if want := messages.T(language, id); !strings.Contains(context, want) {
			t.Errorf("context %q does not contain %q", context, want)
		}
	}
}

func TestDeclarationAcceptsAnyPathAndSymlinks(t *testing.T) {
	f := newFixture(t)
	link := filepath.Join(f.dir, "link.go")
	if err := os.Symlink(f.path("gen.go"), link); err != nil {
		t.Fatal(err)
	}
	expectInjection(t, f.bash("s", declare("link.go")), hooktest.Options{})
	expectInjection(t, f.payload("s", "Edit", map[string]any{"file_path": f.path("gen.go")}), hooktest.Options{})
	// 生成ファイルでないパスの宣言も記録し、受け付けたことを伝える（編集は元から止めない）。
	expectInjection(t, f.bash("s", declare("plain.go")), hooktest.Options{})
}

func TestMalformedDeclarationIsNotRecorded(t *testing.T) {
	f := newFixture(t)
	for _, command := range []string{
		"hhx " + DeclareCommand + " gen.go",
		"hhx " + DeclareCommand + " --reason '' gen.go",
		"hhx " + DeclareCommand + " --reason 'x'",
		"hhx " + DeclareCommand + " --force --reason x gen.go",
		"hhx " + DeclareCommand + " --reason x $FILE",
		"echo hhx " + DeclareCommand + " --reason x gen.go",
	} {
		expectSilent(t, f.bash("s", command), hooktest.Options{})
	}
	expectDeny(t, f.payload("s", "Edit", map[string]any{"file_path": f.path("gen.go")}), hooktest.Options{})
}

func TestDeclarationWithoutSessionIsNotRecorded(t *testing.T) {
	f := newFixture(t)
	expectSilent(t, f.bash("", declare("gen.go")), hooktest.Options{})
	expectDeny(t, f.payload("", "Edit", map[string]any{"file_path": f.path("gen.go")}), hooktest.Options{})
}

func TestDeclarationPrunesOldSessions(t *testing.T) {
	f := newFixture(t)
	st, err := openStore()
	if err != nil {
		t.Fatal(err)
	}
	if err := st.save("old", "reason", []string{f.path("gen.go")}, time.Now()); err != nil {
		t.Fatal(err)
	}
	old := time.Now().Add(-stateTTL - time.Hour)
	if err := os.Chtimes(st.sessionDir("old"), old, old); err != nil {
		t.Fatal(err)
	}
	expectInjection(t, f.bash("new", declare("gen.go")), hooktest.Options{})
	if _, err := os.Stat(st.sessionDir("old")); !os.IsNotExist(err) {
		t.Errorf("the expired session must be removed: %v", err)
	}
	if _, ok := st.lookup("new", f.path("gen.go")); !ok {
		t.Error("the new declaration must be recorded")
	}
	info, err := os.Stat(st.sessionDir("new"))
	if err != nil || info.Mode().Perm() != 0o700 {
		t.Errorf("session directory must be 0700: %v %v", info, err)
	}
}

// --- 経路と奇妙な入力 -----------------------------------------------------------------

func TestArgvAcceptsPayloadAndCommand(t *testing.T) {
	f := newFixture(t)
	t.Chdir(f.dir)
	edit := f.payload("s", "Edit", map[string]any{"file_path": f.path("gen.go")})
	for _, arg := range []string{edit, "echo x > gen.go", "sed -i 's/a/b/' x_mock.go"} {
		if got := hooktest.Argv(t, Definition(), arg); got.Decision != hooktest.Deny {
			t.Errorf("argv %q: decision=%q, want deny", arg, got.Decision)
		}
	}
	if got := hooktest.Argv(t, Definition(), "make autogen > /dev/null"); got.Decision != "" {
		t.Errorf("argv make autogen: decision=%q", got.Decision)
	}
	// デバッグ経路には session_id が無いので、宣言は記録しない。
	if output := hooktest.Output(t, Definition(), "", hooktest.Options{Args: []string{declare("gen.go")}}); output != "" {
		t.Errorf("a declaration without a session must not be recorded: %q", output)
	}
}

func TestOddInputsAreSilent(t *testing.T) {
	f := newFixture(t)
	for _, raw := range []string{
		"", "null", "[]", "{}", "not json > gen.go", `{"tool_name":"Bash"}`,
		`{"tool_name":"Bash","tool_input":{"command":1}}`,
		`{"tool_name":"Bash","tool_input":"echo x > gen.go"}`,
		`{"tool_name":"Bash","tool_input":null}`,
		`{"tool_name":"Bash","tool_input":[]}`,
		`{"tool_name":"Bash","tool_input":{"command":""}}`,
	} {
		expectSilent(t, raw, hooktest.Options{})
	}
	// tool_name が無ければ Bash として読む。cwd が無ければプロセスの作業ディレクトリを使う。
	t.Chdir(f.dir)
	expectDeny(t, `{"tool_input":{"command":"echo x > gen.go"}}`, hooktest.Options{})
}

func TestDisabledHookIsSilent(t *testing.T) {
	f := newFixture(t)
	options := hooktest.Options{Config: "hooks:\n  generated-edit-guard:\n    enabled: false\n"}
	expectSilent(t, f.bash("s", "echo x > gen.go"), options)
	expectSilent(t, f.payload("s", "Edit", map[string]any{"file_path": f.path("gen.go")}), options)
}

func TestInvalidMarkerSettingsKeepStandardMarker(t *testing.T) {
	f := newFixture(t)
	for _, config := range []string{
		"hooks:\n  generated-edit-guard:\n    markers: [\"(\", \"\"]\n",
		"hooks:\n  generated-edit-guard:\n    markers: 3\n",
	} {
		expectDeny(t, f.bash("s", "echo x > gen.go"), hooktest.Options{Config: config})
	}
}

func TestGate(t *testing.T) {
	for _, raw := range []string{"ls -la", "git status", "make autogen", "go test ./..."} {
		if gate([]byte(raw)) {
			t.Errorf("gate(%q) must be false", raw)
		}
	}
	for _, raw := range []string{"echo x > a", `echo x \u003e a`, "sed -i x a", `{"file_path":"/a"}`,
		"*** Update File: a", "hhx " + DeclareCommand} {
		if !gate([]byte(raw)) {
			t.Errorf("gate(%q) must be true", raw)
		}
	}
	// ゲートで抜ける入力は、生成ファイルを指していても判定しない。
	f := newFixture(t)
	expectSilent(t, f.bash("s", "rm gen.go"), hooktest.Options{})
}

// --- 文面 -----------------------------------------------------------------------

// TestInjectionFitsCodexLimit は、両言語で最長になる注入の文面が Codex の additionalContextLimit に収まることを確かめる。
func TestInjectionFitsCodexLimit(t *testing.T) {
	long := strings.Repeat("長", 1000)
	var items []reportItem
	for index := range maxListed + 3 {
		items = append(items, reportItem{
			path:    "/" + strings.Repeat("d", 400) + "/" + strings.Repeat("f", index+1) + ".go",
			reason:  long + strings.Repeat("r", index),
			command: "mockgen " + strings.Repeat("-x ", 200) + strings.Repeat("y", index),
		})
	}
	for _, language := range []i18n.Language{i18n.English, i18n.Japanese} {
		text := reportContext(language, items, items, "/")
		if len(text) > contextLimit {
			t.Errorf("%s: injection is %d bytes, over the %d-byte limit", language, len(text), contextLimit)
		}
	}
}

func TestDenyReasonLists(t *testing.T) {
	var blocked []generated
	for index := range maxListed + 2 {
		blocked = append(blocked, generated{
			path:    "/repo/" + strings.Repeat("g", index+1) + ".go",
			marker:  "// Code generated by acme. DO NOT EDIT.",
			command: "make gen",
		})
	}
	reason := denyReason(hooktest.Language, blocked, "/repo")
	more := messages.Text(hooktest.Language, idMore, map[string]any{"Count": 2})
	if !strings.Contains(reason, more) || strings.Count(reason, "`make gen`") != 1 {
		t.Errorf("reason does not summarize the list: %q", reason)
	}
	if !strings.Contains(reason, "--reason \""+messages.T(hooktest.Language, idDeclarePlaceholder)+"\"") {
		t.Errorf("reason does not show how to declare: %q", reason)
	}
	if strings.Contains(reason, "ask the user") || strings.Contains(reason, "確認") {
		t.Errorf("reason must not ask for a confirmation: %q", reason)
	}
}
