package generatededitguard

import (
	"errors"
	"path/filepath"
	"reflect"
	"strings"
	"syscall"
	"testing"

	"github.com/HappyOnigiri/hhx/internal/hooktest"
)

func TestDetectMarkers(t *testing.T) {
	dir := hooktest.TempDir(t)
	files := map[string]string{
		"crlf.go":     "// Code generated by acme-gen. DO NOT EDIT.\r\n\r\npackage acme\r\n",
		"later.go":    "// Copyright acme\n\n// Code generated by acme-gen. DO NOT EDIT.\npackage acme\n",
		"far.go":      strings.Repeat("\n", headSize) + "// Code generated by acme-gen. DO NOT EDIT.\n",
		"inline.go":   "x := \"// Code generated by acme-gen. DO NOT EDIT.\"\n",
		"stringer.go": "// Code generated by \"stringer -type=Pill\"; DO NOT EDIT.\n",
		"mock.go":     mockHeader,
		"l10n.go":     l10nHeader,
		"noquote.go":  "// Code generated by yo. DO NOT EDIT.\n",
	}
	for name, content := range files {
		hooktest.WriteFile(t, filepath.Join(dir, name), content)
	}
	markers := newMarkerSet([]string{"^// auto generate by 'make l10n'", "(", " "})
	for _, testCase := range []struct {
		name, command string
		want          bool
	}{
		{"crlf.go", "", true},
		{"later.go", "", true},
		{"far.go", "", false},
		{"inline.go", "", false},
		{"stringer.go", "stringer -type=Pill", true},
		{"mock.go", "mockgen -source=acme.go -destination=x_mock.go", true},
		{"l10n.go", "make l10n", true},
		{"noquote.go", "", true},
		{"missing.go", "", false},
		{".", "", false},
	} {
		found, ok := markers.detect(filepath.Join(dir, testCase.name))
		if ok != testCase.want || found.command != testCase.command {
			t.Errorf("%s: detected=%v command=%q, want %v %q", testCase.name, ok, found.command, testCase.want, testCase.command)
		}
		if ok && strings.ContainsAny(found.marker, "\r\n") {
			t.Errorf("%s: marker line %q must not carry line breaks", testCase.name, found.marker)
		}
	}
	// FIFO は開かずに対象外にする（読み込みで止まらない）。
	fifo := filepath.Join(dir, "fifo.go")
	if err := syscall.Mkfifo(fifo, 0o600); err != nil {
		t.Skip(err)
	}
	if _, ok := markers.detect(fifo); ok {
		t.Error("a FIFO must not be treated as a generated file")
	}
}

func TestGeneratorCommandNeedsACommandShape(t *testing.T) {
	for line, want := range map[string]string{
		"// Code generated by 'Acme'. DO NOT EDIT.":                     "",
		"// auto generate by 'make l10n' on repository root directory.": "make l10n",
		"// generated by `go generate ./...`":                           "go generate ./...",
		"// generated by 'x'":                                           "",
	} {
		if got := generatorCommand(line, line); got != want {
			t.Errorf("generatorCommand(%q)=%q, want %q", line, got, want)
		}
	}
}

func TestParseDeclaration(t *testing.T) {
	got, err := ParseDeclaration([]string{"--reason=fix typo", "a.go", "--", "--b.go"})
	if err != nil || got.Reason != "fix typo" || !reflect.DeepEqual(got.Paths, []string{"a.go", "--b.go"}) {
		t.Fatalf("got %+v %v", got, err)
	}
	got, err = ParseDeclaration([]string{"a.go", "--reason", "x", "-"})
	if err != nil || !reflect.DeepEqual(got.Paths, []string{"a.go", "-"}) {
		t.Fatalf("got %+v %v", got, err)
	}
	for _, testCase := range []struct {
		args []string
		want error
	}{
		{nil, ErrNoReason},
		{[]string{"a.go", "--reason"}, ErrNoReason},
		{[]string{"--reason", " ", "a.go"}, ErrNoReason},
		{[]string{"--reason", "x"}, ErrNoPaths},
		{[]string{"-f", "--reason", "x", "a.go"}, UnknownOptionError{Option: "-f"}},
	} {
		if _, err := ParseDeclaration(testCase.args); !errors.Is(err, testCase.want) {
			t.Errorf("%q: err=%v, want %v", testCase.args, err, testCase.want)
		}
	}
	if (UnknownOptionError{Option: "-f"}).Error() != "unknown option: -f" {
		t.Error("UnknownOptionError message")
	}
}
