package generatededitguard

import (
	"io"
	"os"
	"regexp"
	"strings"
)

// headSize はマーカーを探すファイルの先頭の大きさである。生成器はマーカーを先頭の数行に書くので、全体は読まない。
const headSize = 8 << 10

// standardMarker は Go の生成ファイルの標準のマーカー（https://go.dev/s/generatedcode）である。
// CRLF のファイルでも一致させるため、行末の \r を許す。
var standardMarker = regexp.MustCompile(`(?m)^// Code generated .* DO NOT EDIT\.\r?$`)

// generated は生成ファイルと判定したファイルである。
type generated struct {
	// path は判定に使った絶対パスである。
	path string
	// marker は一致したマーカーの行である。
	marker string
	// command はマーカーから読めた生成コマンドで、読めなければ空文字列である。
	command string
}

// markerSet は判定に使うマーカーの一覧である（標準のマーカーと、設定に書かれた正規表現）。
type markerSet []*regexp.Regexp

// newMarkerSet は設定のマーカーを (?m) つきで compile して標準のマーカーの後ろに並べる。
// compile できない正規表現は無視する（hook は止めない。install の検査は型までしか見ない）。
func newMarkerSet(extra []string) markerSet {
	set := markerSet{standardMarker}
	for _, expression := range extra {
		if strings.TrimSpace(expression) == "" {
			continue
		}
		if compiled, err := regexp.Compile(`(?m)` + expression); err == nil {
			set = append(set, compiled)
		}
	}
	return set
}

// detect は path が実在する通常のファイルで、先頭にマーカーがあれば判定の結果を返す。
// 存在しないパス（新規作成）・ディレクトリ・特殊なファイル（FIFO で読み込みが止まらないよう、開く前に確かめる）は対象外である。
func (m markerSet) detect(path string) (generated, bool) {
	info, err := os.Stat(path)
	if err != nil || !info.Mode().IsRegular() {
		return generated{}, false
	}
	file, err := os.Open(path)
	if err != nil {
		return generated{}, false
	}
	defer func() { _ = file.Close() }()
	head, err := io.ReadAll(io.LimitReader(file, headSize))
	if err != nil {
		return generated{}, false
	}
	text := string(head)
	for _, marker := range m {
		location := marker.FindStringIndex(text)
		if location == nil {
			continue
		}
		line := lineAt(text, location[0])
		return generated{path: path, marker: line, command: generatorCommand(text, line)}, true
	}
	return generated{}, false
}

// lineAt は text の offset を含む行を、行末の \r を除いて返す。
func lineAt(text string, offset int) string {
	start := strings.LastIndexByte(text[:offset], '\n') + 1
	end := strings.IndexByte(text[offset:], '\n')
	line := text[start:]
	if end >= 0 {
		line = text[start : offset+end]
	}
	return strings.TrimRight(line, "\r")
}

var (
	// quotedCommandRE はマーカーの行の中のクォートで囲んだ生成コマンド（'make l10n'、"stringer -type=Pill"、`go generate`）である。
	quotedCommandRE = regexp.MustCompile("'([^'\n]+)'|\"([^\"\n]+)\"|`([^`\n]+)`")
	// mockgenCommandRE は mockgen が書く「Generated by this command:」の次のコマンドの行である。
	mockgenCommandRE = regexp.MustCompile(`(?m)^// Generated by this command:\r?\n//\r?\n//[\t ]+(\S[^\r\n]*)`)
	// commandLikeRE は生成コマンドらしい値（英小文字で始まるコマンド名の後ろに引数が続く）である。
	commandLikeRE = regexp.MustCompile(`^[a-z][A-Za-z0-9_.-]*(?:/[A-Za-z0-9_.-]+)*\s+\S`)
)

// generatorCommand はマーカーの行と先頭から生成コマンドを読む。読めなければ空文字列を返す。
func generatorCommand(head, line string) string {
	for _, match := range quotedCommandRE.FindAllStringSubmatch(line, -1) {
		for _, group := range match[1:] {
			if candidate := strings.TrimSpace(group); commandLikeRE.MatchString(candidate) {
				return candidate
			}
		}
	}
	if match := mockgenCommandRE.FindStringSubmatch(head); match != nil {
		return strings.TrimSpace(match[1])
	}
	return ""
}
